### ISSUE TITLE
Using the Camera to Take a Picture needs Vue.js and Core examples

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/code-samples#11]
[Angular version](https://play.nativescript.org/?template=play-ng&id=A218zg&v=3) needs Vue.js and Core examples created

**Comment by shiv19** [comment]
Vue and Core have been implemented

**Comment by tjvantoll** [comment]
Merged with @shiv19’s ba460058e81da8248215a18819e02842c971fe0a commit.
