### ISSUE TITLE
Building a Good-Looking Login Form

### ISSUE THREAD

**Issue by drophit** [NativeScript/code-samples#131]
The JS Core version of this does not work - Angular and Vue work as expected however the JS version does not actually "login" and returns the same catch result. This is frustrating to beginners trying to learn NativeScript JS Core - is there another Loginform JS version we can review?

**Comment by tjvantoll** [comment]
Thanks for reporting this @drophit! There was a small problem with the navigation code (basically a typo in `app.js`) that I just patched. I also added the ActivityIndicator that was in the Angular version.

The fixed version is at https://play.nativescript.org/?template=play-js&id=h9CNcL&v=3542 if you want to check it out, and it’ll be live on the site with the next release.
