### ISSUE TITLE
Float-up labels needs a Core version

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/code-samples#15]
Angular version: https://play.nativescript.org/?template=play-ng&id=9GOYmZ&v=6
Vue version: https://play.nativescript.org/?template=play-vue&id=WlzgRU&v=10
Core version: doesn’t exist, this is what needs to be built :)

**Comment by shiv19** [comment]
In the angular version, GridLayout has not been closed properly
![image](https://user-images.githubusercontent.com/9407019/43731403-04f36520-99cc-11e8-9c7c-576178d28264.png)

So use this version: https://play.nativescript.org/?template=play-ng&id=9GOYmZ&v=59

**Comment by shiv19** [comment]
TADAAA:
Implemented it for Core
https://play.nativescript.org/?template=play-js&id=oSksgv

**Comment by rdlauer** [comment]
Thanks @shiv19 !
