### ISSUE TITLE
Getting a User’s Current Location needs Angular

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/code-samples#17]
Has a [Vue.js](https://play.nativescript.org/?template=play-vue&id=xYes1e&v=2) and [Core[(https://play.nativescript.org/?template=play-tsc&id=veTP4B&v=2) example, but needs Angular.

**Comment by shiv19** [comment]
@rdlauer 
I've created an Angular sample for the same :)
Cheers!

**Comment by tjvantoll** [comment]
Fixed with @shiv19’s b5c82bdf8fce6a03a67404081ccf85785413e254 commit.
