### ISSUE TITLE
All the versions (vue, ng, ...) icons links go to the ng version if no filter is selected 

### ISSUE THREAD

**Issue by msaelices** [NativeScript/code-samples#34]
If there is no filter selected (i.e `vue`) all the icon links go to the `ng` version.

https://market.nativescript.org/?tab=samples

The expected behavior is that the `vue` icon goes to the `vue` version, etc.

**Comment by rdlauer** [comment]
In its current state, there is *always* a framework selected, so if you click anywhere in the sample box (even on a different icon), it'll open the framework associated with what is selected at the top. However, we already have a new UI in the works to make this more clear. Thanks for the note!
