### ISSUE TITLE
Social Network needs angular

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/code-samples#93]
https://play.nativescript.org/?template=play-js&id=O581mC&v=38

**Comment by jaasaria** [comment]
Hi Rdlauer, here's for vuejs please kindly check: 
https://play.nativescript.org/?template=play-vue&id=ZiXWFo&v=5

**Comment by rdlauer** [comment]
Looks great, thanks!

**Comment by salvadorcoronel** [comment]
Hi Rob, I'm working on adding Angular.

**Comment by salvadorcoronel** [comment]
Hi Rob,
Here is the link of the demo in angular 
[(https://play.nativescript.org/?template=play-ng&id=kfKgN2&v=2)]

**Comment by rdlauer** [comment]
Thanks!
